import {
  SiAlgolia,
  SiAndroid,
  SiAngular,
  SiAntdesign,
  SiAnthropic,
  SiApollographql,
  SiApple,
  SiAppwrite,
  SiAstro,
  SiAuth0,
  SiBitbucket,
  SiBlender,
  SiBootstrap,
  SiBun,
  SiCapacitor,
  SiChakraui,
  SiChartdotjs,
  SiCircleci,
  SiClaude,
  SiClerk,
  SiClickhouse,
  SiCloudflare,
  SiContentful,
  SiCss,
  SiCursor,
  SiCypress,
  SiD3,
  SiDart,
  SiDeepseek,
  SiDeno,
  SiDigitalocean,
  SiDiscord,
  SiDjango,
  SiDocker,
  SiDrizzle,
  SiElasticsearch,
  SiElectron,
  SiEslint,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiFlydotio,
  SiFramer,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGithubcopilot,
  SiGitlab,
  SiGo,
  SiGooglecloud,
  SiGooglegemini,
  SiGooglemaps,
  SiGrafana,
  SiGraphql,
  SiGreensock,
  SiHasura,
  SiHeadlessui,
  SiHono,
  SiHtml5,
  SiHuggingface,
  SiIonic,
  SiJavascript,
  SiJest,
  SiJira,
  SiJsonwebtokens,
  SiKotlin,
  SiKubernetes,
  SiLangchain,
  SiLaravel,
  SiLeaflet,
  SiLess,
  SiLinear,
  SiLinux,
  SiLottiefiles,
  SiMapbox,
  SiMeilisearch,
  SiMistralai,
  SiMobx,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNotion,
  SiNpm,
  SiNuxt,
  SiOllama,
  SiPaypal,
  SiPerplexity,
  SiPhp,
  SiPinia,
  SiPlanetscale,
  SiPnpm,
  SiPostgresql,
  SiPostman,
  SiPrettier,
  SiPrisma,
  SiPrometheus,
  SiPwa,
  SiPython,
  SiQwik,
  SiRabbitmq,
  SiRadixui,
  SiRailway,
  SiReact,
  SiReactquery,
  SiRedis,
  SiRedux,
  SiRemix,
  SiRender,
  SiRuby,
  SiRust,
  SiSanity,
  SiSass,
  SiSentry,
  SiShadcnui,
  SiShopify,
  SiSocketdotio,
  SiSolid,
  SiSpring,
  SiSqlite,
  SiStorybook,
  SiStrapi,
  SiStripe,
  SiStyledcomponents,
  SiSupabase,
  SiSvelte,
  SiSwagger,
  SiSwift,
  SiTailwindcss,
  SiTauri,
  SiTensorflow,
  SiTerraform,
  SiTestinglibrary,
  SiThreedotjs,
  SiTrello,
  SiTrpc,
  SiTurborepo,
  SiTypescript,
  SiUnity,
  SiV0,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
  SiWebpack,
  SiWindsurf,
  SiWordpress,
  SiYarn,
} from 'react-icons/si'

import type { ITechItem, ITechStackGroup, TechCategory } from '@/types/tech-stack'

export const TECH_STACK_CATEGORY_ORDER: TechCategory[] = [
  'language',
  'frontend',
  'backend',
  'mobile',
  'database',
  'cloud',
  'ai',
  'tooling',
  'design',
  'animation',
  'testing',
  'cms',
  'payment',
]

export const TECH_STACK_CATALOG: ITechItem[] = [
  {
    id: 'html5',
    name: 'HTML5',
    aliases: ['html', 'html 5'],
    category: 'language',
    icon: SiHtml5,
    colorClass: 'text-[#e34f26]',
  },
  {
    id: 'css3',
    name: 'CSS3',
    aliases: ['css'],
    category: 'language',
    icon: SiCss,
    colorClass: 'text-[#1572b6]',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    aliases: ['js', 'javascript (es2023)', 'es2023', 'ecmascript'],
    category: 'language',
    icon: SiJavascript,
    colorClass: 'text-[#f7df1e]',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    aliases: ['ts'],
    category: 'language',
    icon: SiTypescript,
    colorClass: 'text-[#3178c6]',
  },
  {
    id: 'python',
    name: 'Python',
    aliases: ['py'],
    category: 'language',
    icon: SiPython,
    colorClass: 'text-[#3776ab]',
  },
  {
    id: 'go',
    name: 'Go',
    aliases: ['golang'],
    category: 'language',
    icon: SiGo,
    colorClass: 'text-[#00add8]',
  },
  {
    id: 'rust',
    name: 'Rust',
    aliases: [],
    category: 'language',
    icon: SiRust,
    colorClass: 'text-[#dea584]',
  },
  {
    id: 'php',
    name: 'PHP',
    aliases: [],
    category: 'language',
    icon: SiPhp,
    colorClass: 'text-[#777bb4]',
  },
  {
    id: 'ruby',
    name: 'Ruby',
    aliases: [],
    category: 'language',
    icon: SiRuby,
    colorClass: 'text-[#cc342d]',
  },
  {
    id: 'swift',
    name: 'Swift',
    aliases: [],
    category: 'language',
    icon: SiSwift,
    colorClass: 'text-[#f05138]',
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    aliases: [],
    category: 'language',
    icon: SiKotlin,
    colorClass: 'text-[#7f52ff]',
  },
  {
    id: 'dart',
    name: 'Dart',
    aliases: [],
    category: 'language',
    icon: SiDart,
    colorClass: 'text-[#0175c2]',
  },
  {
    id: 'react',
    name: 'React',
    aliases: ['react.js', 'reactjs'],
    category: 'frontend',
    icon: SiReact,
    colorClass: 'text-[#61dafb]',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    aliases: ['next', 'nextjs'],
    category: 'frontend',
    icon: SiNextdotjs,
    colorClass: 'text-foreground dark:text-white',
  },
  {
    id: 'vue',
    name: 'Vue.js',
    aliases: ['vue', 'vuejs'],
    category: 'frontend',
    icon: SiVuedotjs,
    colorClass: 'text-[#42b883]',
  },
  {
    id: 'nuxt',
    name: 'Nuxt',
    aliases: ['nuxt.js', 'nuxtjs'],
    category: 'frontend',
    icon: SiNuxt,
    colorClass: 'text-[#00dc82]',
  },
  {
    id: 'angular',
    name: 'Angular',
    aliases: [],
    category: 'frontend',
    icon: SiAngular,
    colorClass: 'text-[#dd0031]',
  },
  {
    id: 'svelte',
    name: 'Svelte',
    aliases: ['sveltekit'],
    category: 'frontend',
    icon: SiSvelte,
    colorClass: 'text-[#ff3e00]',
  },
  {
    id: 'astro',
    name: 'Astro',
    aliases: [],
    category: 'frontend',
    icon: SiAstro,
    colorClass: 'text-[#ff5d01]',
  },
  {
    id: 'remix',
    name: 'Remix',
    aliases: [],
    category: 'frontend',
    icon: SiRemix,
    colorClass: 'text-foreground',
  },
  {
    id: 'solid',
    name: 'Solid',
    aliases: ['solidjs', 'solid.js'],
    category: 'frontend',
    icon: SiSolid,
    colorClass: 'text-[#2c4f7c]',
  },
  {
    id: 'qwik',
    name: 'Qwik',
    aliases: [],
    category: 'frontend',
    icon: SiQwik,
    colorClass: 'text-[#ac7ef4]',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    aliases: ['tailwind', 'tailwindcss'],
    category: 'frontend',
    icon: SiTailwindcss,
    colorClass: 'text-[#38bdf8]',
  },
  {
    id: 'sass',
    name: 'Sass',
    aliases: ['scss', 'css3 / sass'],
    category: 'frontend',
    icon: SiSass,
    colorClass: 'text-[#cc6699]',
  },
  {
    id: 'less',
    name: 'Less',
    aliases: [],
    category: 'frontend',
    icon: SiLess,
    colorClass: 'text-[#1d365d]',
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    aliases: [],
    category: 'frontend',
    icon: SiBootstrap,
    colorClass: 'text-[#7952b3]',
  },
  {
    id: 'shadcn',
    name: 'shadcn/ui',
    aliases: ['shadcn', 'shadcn ui'],
    category: 'frontend',
    icon: SiShadcnui,
    colorClass: 'text-foreground',
  },
  {
    id: 'radix',
    name: 'Radix UI',
    aliases: ['radix', 'radixui'],
    category: 'frontend',
    icon: SiRadixui,
    colorClass: 'text-foreground',
  },
  {
    id: 'mui',
    name: 'MUI',
    aliases: ['material ui', 'material-ui'],
    category: 'frontend',
    icon: SiMui,
    colorClass: 'text-[#007fff]',
  },
  {
    id: 'chakra',
    name: 'Chakra UI',
    aliases: ['chakra', 'chakraui'],
    category: 'frontend',
    icon: SiChakraui,
    colorClass: 'text-[#319795]',
  },
  {
    id: 'antd',
    name: 'Ant Design',
    aliases: ['antd', 'ant design'],
    category: 'frontend',
    icon: SiAntdesign,
    colorClass: 'text-[#0170fe]',
  },
  {
    id: 'headlessui',
    name: 'Headless UI',
    aliases: [],
    category: 'frontend',
    icon: SiHeadlessui,
    colorClass: 'text-[#66e3ff]',
  },
  {
    id: 'styled-components',
    name: 'Styled Components',
    aliases: ['styled-components'],
    category: 'frontend',
    icon: SiStyledcomponents,
    colorClass: 'text-[#db7093]',
  },
  {
    id: 'redux',
    name: 'Redux',
    aliases: ['redux toolkit', 'rtk'],
    category: 'frontend',
    icon: SiRedux,
    colorClass: 'text-[#764abc]',
  },
  {
    id: 'zustand',
    name: 'Zustand',
    aliases: [],
    category: 'frontend',
    colorClass: 'text-[#443e38]',
  },
  {
    id: 'pinia',
    name: 'Pinia',
    aliases: [],
    category: 'frontend',
    icon: SiPinia,
    colorClass: 'text-[#ffd859]',
  },
  {
    id: 'mobx',
    name: 'MobX',
    aliases: [],
    category: 'frontend',
    icon: SiMobx,
    colorClass: 'text-[#ff9955]',
  },
  {
    id: 'tanstack-query',
    name: 'TanStack Query',
    aliases: ['react query', 'react-query', 'tanstack'],
    category: 'frontend',
    icon: SiReactquery,
    colorClass: 'text-[#ff4154]',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    aliases: ['node', 'nodejs'],
    category: 'backend',
    icon: SiNodedotjs,
    colorClass: 'text-[#5fa04e]',
  },
  {
    id: 'express',
    name: 'Express',
    aliases: ['express.js', 'expressjs'],
    category: 'backend',
    icon: SiExpress,
    colorClass: 'text-foreground',
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    aliases: ['nest'],
    category: 'backend',
    icon: SiNestjs,
    colorClass: 'text-[#e0234e]',
  },
  {
    id: 'hono',
    name: 'Hono',
    aliases: [],
    category: 'backend',
    icon: SiHono,
    colorClass: 'text-[#e36002]',
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    aliases: ['gql'],
    category: 'backend',
    icon: SiGraphql,
    colorClass: 'text-[#e10098]',
  },
  {
    id: 'rest-api',
    name: 'REST API',
    aliases: ['rest', 'restful', 'rest / graphql apis'],
    category: 'backend',
    icon: SiSwagger,
    colorClass: 'text-[#85ea2d]',
  },
  {
    id: 'trpc',
    name: 'tRPC',
    aliases: ['trpc'],
    category: 'backend',
    icon: SiTrpc,
    colorClass: 'text-[#398ccb]',
  },
  {
    id: 'apollo',
    name: 'Apollo GraphQL',
    aliases: ['apollo'],
    category: 'backend',
    icon: SiApollographql,
    colorClass: 'text-[#311c87]',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    aliases: [],
    category: 'backend',
    icon: SiPrisma,
    colorClass: 'text-[#2d3748]',
  },
  {
    id: 'drizzle',
    name: 'Drizzle',
    aliases: ['drizzle orm'],
    category: 'backend',
    icon: SiDrizzle,
    colorClass: 'text-[#c5f74f]',
  },
  {
    id: 'fastapi',
    name: 'FastAPI',
    aliases: [],
    category: 'backend',
    icon: SiFastapi,
    colorClass: 'text-[#009688]',
  },
  {
    id: 'django',
    name: 'Django',
    aliases: [],
    category: 'backend',
    icon: SiDjango,
    colorClass: 'text-[#092e20]',
  },
  {
    id: 'flask',
    name: 'Flask',
    aliases: [],
    category: 'backend',
    icon: SiFlask,
    colorClass: 'text-foreground',
  },
  {
    id: 'laravel',
    name: 'Laravel',
    aliases: [],
    category: 'backend',
    icon: SiLaravel,
    colorClass: 'text-[#ff2d20]',
  },
  {
    id: 'spring',
    name: 'Spring',
    aliases: ['spring boot'],
    category: 'backend',
    icon: SiSpring,
    colorClass: 'text-[#6db33f]',
  },
  {
    id: 'socketio',
    name: 'Socket.IO',
    aliases: ['socket.io', 'websocket'],
    category: 'backend',
    icon: SiSocketdotio,
    colorClass: 'text-foreground',
  },
  {
    id: 'jwt',
    name: 'JWT',
    aliases: ['jsonwebtoken', 'json web token'],
    category: 'backend',
    icon: SiJsonwebtokens,
    colorClass: 'text-foreground',
  },
  {
    id: 'auth0',
    name: 'Auth0',
    aliases: [],
    category: 'backend',
    icon: SiAuth0,
    colorClass: 'text-[#eb5424]',
  },
  {
    id: 'clerk',
    name: 'Clerk',
    aliases: [],
    category: 'backend',
    icon: SiClerk,
    colorClass: 'text-[#6c47ff]',
  },
  {
    id: 'react-native',
    name: 'React Native',
    aliases: ['rn'],
    category: 'mobile',
    icon: SiReact,
    colorClass: 'text-[#61dafb]',
  },
  {
    id: 'expo',
    name: 'Expo',
    aliases: [],
    category: 'mobile',
    icon: SiExpo,
    colorClass: 'text-foreground',
  },
  {
    id: 'flutter',
    name: 'Flutter',
    aliases: [],
    category: 'mobile',
    icon: SiFlutter,
    colorClass: 'text-[#02569b]',
  },
  {
    id: 'ionic',
    name: 'Ionic',
    aliases: [],
    category: 'mobile',
    icon: SiIonic,
    colorClass: 'text-[#3880ff]',
  },
  {
    id: 'capacitor',
    name: 'Capacitor',
    aliases: [],
    category: 'mobile',
    icon: SiCapacitor,
    colorClass: 'text-[#119eff]',
  },
  {
    id: 'android',
    name: 'Android',
    aliases: [],
    category: 'mobile',
    icon: SiAndroid,
    colorClass: 'text-[#3ddc84]',
  },
  {
    id: 'ios',
    name: 'iOS',
    aliases: ['apple', 'swiftui'],
    category: 'mobile',
    icon: SiApple,
    colorClass: 'text-foreground',
  },
  {
    id: 'pwa',
    name: 'PWA',
    aliases: ['progressive web app'],
    category: 'mobile',
    icon: SiPwa,
    colorClass: 'text-[#5a0fc8]',
  },
  {
    id: 'electron',
    name: 'Electron',
    aliases: [],
    category: 'mobile',
    icon: SiElectron,
    colorClass: 'text-[#47848f]',
  },
  {
    id: 'tauri',
    name: 'Tauri',
    aliases: [],
    category: 'mobile',
    icon: SiTauri,
    colorClass: 'text-[#ffc131]',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    aliases: ['postgres', 'psql'],
    category: 'database',
    icon: SiPostgresql,
    colorClass: 'text-[#336791]',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    aliases: [],
    category: 'database',
    icon: SiMysql,
    colorClass: 'text-[#4479a1]',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    aliases: [],
    category: 'database',
    icon: SiSqlite,
    colorClass: 'text-[#003b57]',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    aliases: ['mongo'],
    category: 'database',
    icon: SiMongodb,
    colorClass: 'text-[#47a248]',
  },
  {
    id: 'redis',
    name: 'Redis',
    aliases: [],
    category: 'database',
    icon: SiRedis,
    colorClass: 'text-[#ff4438]',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    aliases: [],
    category: 'database',
    icon: SiFirebase,
    colorClass: 'text-[#ffca28]',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    aliases: [],
    category: 'database',
    icon: SiSupabase,
    colorClass: 'text-[#3ecf8e]',
  },
  {
    id: 'appwrite',
    name: 'Appwrite',
    aliases: [],
    category: 'database',
    icon: SiAppwrite,
    colorClass: 'text-[#fd366e]',
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    aliases: [],
    category: 'database',
    icon: SiPlanetscale,
    colorClass: 'text-foreground',
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    aliases: [],
    category: 'database',
    icon: SiClickhouse,
    colorClass: 'text-[#ffcc01]',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    aliases: ['elastic'],
    category: 'database',
    icon: SiElasticsearch,
    colorClass: 'text-[#005571]',
  },
  {
    id: 'algolia',
    name: 'Algolia',
    aliases: [],
    category: 'database',
    icon: SiAlgolia,
    colorClass: 'text-[#003dff]',
  },
  {
    id: 'meilisearch',
    name: 'Meilisearch',
    aliases: [],
    category: 'database',
    icon: SiMeilisearch,
    colorClass: 'text-[#ff5caa]',
  },
  {
    id: 'hasura',
    name: 'Hasura',
    aliases: [],
    category: 'database',
    icon: SiHasura,
    colorClass: 'text-[#1eb4d4]',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    aliases: [],
    category: 'cloud',
    icon: SiVercel,
    colorClass: 'text-foreground',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    aliases: [],
    category: 'cloud',
    icon: SiNetlify,
    colorClass: 'text-[#00c7b7]',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    aliases: ['cf workers', 'cloudflare workers'],
    category: 'cloud',
    icon: SiCloudflare,
    colorClass: 'text-[#f38020]',
  },
  {
    id: 'google-cloud',
    name: 'Google Cloud',
    aliases: ['gcp'],
    category: 'cloud',
    icon: SiGooglecloud,
    colorClass: 'text-[#4285f4]',
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    aliases: ['do'],
    category: 'cloud',
    icon: SiDigitalocean,
    colorClass: 'text-[#0080ff]',
  },
  {
    id: 'render',
    name: 'Render',
    aliases: [],
    category: 'cloud',
    icon: SiRender,
    colorClass: 'text-foreground',
  },
  {
    id: 'railway',
    name: 'Railway',
    aliases: [],
    category: 'cloud',
    icon: SiRailway,
    colorClass: 'text-[#0b0d0e]',
  },
  {
    id: 'flyio',
    name: 'Fly.io',
    aliases: ['fly'],
    category: 'cloud',
    icon: SiFlydotio,
    colorClass: 'text-[#8b5cf6]',
  },
  {
    id: 'docker',
    name: 'Docker',
    aliases: [],
    category: 'cloud',
    icon: SiDocker,
    colorClass: 'text-[#2496ed]',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    aliases: ['k8s'],
    category: 'cloud',
    icon: SiKubernetes,
    colorClass: 'text-[#326ce5]',
  },
  {
    id: 'nginx',
    name: 'Nginx',
    aliases: [],
    category: 'cloud',
    icon: SiNginx,
    colorClass: 'text-[#009639]',
  },
  {
    id: 'linux',
    name: 'Linux',
    aliases: ['ubuntu', 'debian'],
    category: 'cloud',
    icon: SiLinux,
    colorClass: 'text-[#fcc624]',
  },
  {
    id: 'git',
    name: 'Git',
    aliases: [],
    category: 'tooling',
    icon: SiGit,
    colorClass: 'text-[#f1502f]',
  },
  {
    id: 'github',
    name: 'GitHub',
    aliases: [],
    category: 'tooling',
    icon: SiGithub,
    colorClass: 'text-foreground',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    aliases: [],
    category: 'tooling',
    icon: SiGitlab,
    colorClass: 'text-[#fc6d26]',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    aliases: [],
    category: 'tooling',
    icon: SiBitbucket,
    colorClass: 'text-[#0052cc]',
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    aliases: ['ci', 'cd'],
    category: 'tooling',
    icon: SiGithubactions,
    colorClass: 'text-[#2088ff]',
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    aliases: [],
    category: 'tooling',
    icon: SiCircleci,
    colorClass: 'text-foreground',
  },
  {
    id: 'vite',
    name: 'Vite',
    aliases: [],
    category: 'tooling',
    icon: SiVite,
    colorClass: 'text-[#8b5cf6]',
  },
  {
    id: 'webpack',
    name: 'Webpack',
    aliases: [],
    category: 'tooling',
    icon: SiWebpack,
    colorClass: 'text-[#1c78c0]',
  },
  {
    id: 'turborepo',
    name: 'Turborepo',
    aliases: ['turbo'],
    category: 'tooling',
    icon: SiTurborepo,
    colorClass: 'text-[#ef4444]',
  },
  {
    id: 'eslint',
    name: 'ESLint',
    aliases: ['eslint / prettier'],
    category: 'tooling',
    icon: SiEslint,
    colorClass: 'text-[#4b32c3]',
  },
  {
    id: 'prettier',
    name: 'Prettier',
    aliases: ['eslint / prettier'],
    category: 'tooling',
    icon: SiPrettier,
    colorClass: 'text-[#f7b93e]',
  },
  {
    id: 'bun',
    name: 'Bun',
    aliases: [],
    category: 'tooling',
    icon: SiBun,
    colorClass: 'text-[#f9f1e1]',
  },
  {
    id: 'pnpm',
    name: 'pnpm',
    aliases: [],
    category: 'tooling',
    icon: SiPnpm,
    colorClass: 'text-[#f69220]',
  },
  {
    id: 'npm',
    name: 'npm',
    aliases: [],
    category: 'tooling',
    icon: SiNpm,
    colorClass: 'text-[#cb3837]',
  },
  {
    id: 'yarn',
    name: 'Yarn',
    aliases: [],
    category: 'tooling',
    icon: SiYarn,
    colorClass: 'text-[#2c8ebb]',
  },
  {
    id: 'deno',
    name: 'Deno',
    aliases: [],
    category: 'tooling',
    icon: SiDeno,
    colorClass: 'text-foreground',
  },
  {
    id: 'postman',
    name: 'Postman',
    aliases: [],
    category: 'tooling',
    icon: SiPostman,
    colorClass: 'text-[#ff6c37]',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    aliases: [],
    category: 'tooling',
    icon: SiSentry,
    colorClass: 'text-[#362d59]',
  },
  {
    id: 'terraform',
    name: 'Terraform',
    aliases: [],
    category: 'tooling',
    icon: SiTerraform,
    colorClass: 'text-[#7b42bc]',
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    aliases: [],
    category: 'tooling',
    icon: SiPrometheus,
    colorClass: 'text-[#e6522c]',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    aliases: [],
    category: 'tooling',
    icon: SiGrafana,
    colorClass: 'text-[#f46800]',
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    aliases: [],
    category: 'tooling',
    icon: SiRabbitmq,
    colorClass: 'text-[#ff6600]',
  },
  {
    id: 'figma',
    name: 'Figma',
    aliases: [],
    category: 'design',
    icon: SiFigma,
    colorClass: 'text-[#f24e1e]',
  },
  {
    id: 'storybook',
    name: 'Storybook',
    aliases: [],
    category: 'design',
    icon: SiStorybook,
    colorClass: 'text-[#ff4785]',
  },
  {
    id: 'blender',
    name: 'Blender',
    aliases: [],
    category: 'design',
    icon: SiBlender,
    colorClass: 'text-[#e87d0d]',
  },
  {
    id: 'notion',
    name: 'Notion',
    aliases: [],
    category: 'design',
    icon: SiNotion,
    colorClass: 'text-foreground',
  },
  {
    id: 'linear',
    name: 'Linear',
    aliases: [],
    category: 'design',
    icon: SiLinear,
    colorClass: 'text-[#5e6ad2]',
  },
  {
    id: 'jira',
    name: 'Jira',
    aliases: [],
    category: 'design',
    icon: SiJira,
    colorClass: 'text-[#0052cc]',
  },
  {
    id: 'trello',
    name: 'Trello',
    aliases: [],
    category: 'design',
    icon: SiTrello,
    colorClass: 'text-[#0052cc]',
  },
  {
    id: 'gsap',
    name: 'GSAP',
    aliases: ['greensock'],
    category: 'animation',
    icon: SiGreensock,
    colorClass: 'text-[#88ce02]',
  },
  {
    id: 'framer-motion',
    name: 'Framer Motion',
    aliases: ['motion', 'motion (framer motion)', 'framer'],
    category: 'animation',
    icon: SiFramer,
    colorClass: 'text-[#0055ff]',
  },
  {
    id: 'threejs',
    name: 'Three.js',
    aliases: ['three', 'webgl'],
    category: 'animation',
    icon: SiThreedotjs,
    colorClass: 'text-foreground',
  },
  {
    id: 'lottie',
    name: 'Lottie',
    aliases: ['lottiefiles', 'css animations'],
    category: 'animation',
    icon: SiLottiefiles,
    colorClass: 'text-[#00ddb3]',
  },
  {
    id: 'd3',
    name: 'D3.js',
    aliases: ['d3'],
    category: 'animation',
    icon: SiD3,
    colorClass: 'text-[#f9a03c]',
  },
  {
    id: 'chartjs',
    name: 'Chart.js',
    aliases: ['chartjs'],
    category: 'animation',
    icon: SiChartdotjs,
    colorClass: 'text-[#ff6384]',
  },
  {
    id: 'mapbox',
    name: 'Mapbox',
    aliases: [],
    category: 'animation',
    icon: SiMapbox,
    colorClass: 'text-foreground',
  },
  {
    id: 'google-maps',
    name: 'Google Maps API',
    aliases: ['google maps', 'maps'],
    category: 'animation',
    icon: SiGooglemaps,
    colorClass: 'text-[#4285f4]',
  },
  {
    id: 'leaflet',
    name: 'Leaflet',
    aliases: [],
    category: 'animation',
    icon: SiLeaflet,
    colorClass: 'text-[#199900]',
  },
  {
    id: 'unity',
    name: 'Unity',
    aliases: [],
    category: 'animation',
    icon: SiUnity,
    colorClass: 'text-foreground',
  },
  {
    id: 'jest',
    name: 'Jest',
    aliases: [],
    category: 'testing',
    icon: SiJest,
    colorClass: 'text-[#c21325]',
  },
  {
    id: 'vitest',
    name: 'Vitest',
    aliases: [],
    category: 'testing',
    icon: SiVitest,
    colorClass: 'text-[#729b1b]',
  },
  {
    id: 'playwright',
    name: 'Playwright',
    aliases: [],
    category: 'testing',
    colorClass: 'text-[#2ead33]',
  },
  {
    id: 'cypress',
    name: 'Cypress',
    aliases: [],
    category: 'testing',
    icon: SiCypress,
    colorClass: 'text-[#69d3a7]',
  },
  {
    id: 'testing-library',
    name: 'Testing Library',
    aliases: ['react testing library', 'rtl'],
    category: 'testing',
    icon: SiTestinglibrary,
    colorClass: 'text-[#e33332]',
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    aliases: ['wp'],
    category: 'cms',
    icon: SiWordpress,
    colorClass: 'text-[#21759b]',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    aliases: [],
    category: 'cms',
    icon: SiShopify,
    colorClass: 'text-[#7ab55c]',
  },
  {
    id: 'sanity',
    name: 'Sanity',
    aliases: [],
    category: 'cms',
    icon: SiSanity,
    colorClass: 'text-[#f03e2f]',
  },
  {
    id: 'contentful',
    name: 'Contentful',
    aliases: [],
    category: 'cms',
    icon: SiContentful,
    colorClass: 'text-[#2478cc]',
  },
  {
    id: 'strapi',
    name: 'Strapi',
    aliases: [],
    category: 'cms',
    icon: SiStrapi,
    colorClass: 'text-[#4945ff]',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    aliases: [],
    category: 'payment',
    icon: SiStripe,
    colorClass: 'text-[#635bff]',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    aliases: [],
    category: 'payment',
    icon: SiPaypal,
    colorClass: 'text-[#003087]',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    aliases: ['chatgpt', 'gpt'],
    category: 'ai',
    colorClass: 'text-foreground',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    aliases: [],
    category: 'ai',
    icon: SiAnthropic,
    colorClass: 'text-[#d4a27f]',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    aliases: [],
    category: 'ai',
    icon: SiOllama,
    colorClass: 'text-foreground',
  },
  {
    id: 'langchain',
    name: 'LangChain',
    aliases: [],
    category: 'ai',
    icon: SiLangchain,
    colorClass: 'text-[#1c3c3c]',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    aliases: ['hf'],
    category: 'ai',
    icon: SiHuggingface,
    colorClass: 'text-[#ffd21e]',
  },
  {
    id: 'claude',
    name: 'Claude',
    aliases: ['claude code', 'claude ai'],
    category: 'ai',
    icon: SiClaude,
    colorClass: 'text-[#d97757]',
  },
  {
    id: 'codex',
    name: 'Codex',
    aliases: ['openai codex'],
    category: 'ai',
    colorClass: 'text-foreground',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    aliases: ['cursor ai'],
    category: 'ai',
    icon: SiCursor,
    colorClass: 'text-foreground',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    aliases: ['copilot'],
    category: 'ai',
    icon: SiGithubcopilot,
    colorClass: 'text-foreground',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    aliases: ['google gemini', 'bard'],
    category: 'ai',
    icon: SiGooglegemini,
    colorClass: 'text-[#8e75b2]',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    aliases: [],
    category: 'ai',
    icon: SiPerplexity,
    colorClass: 'text-[#20808d]',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    aliases: [],
    category: 'ai',
    icon: SiDeepseek,
    colorClass: 'text-[#4d6bfe]',
  },
  {
    id: 'mistral-ai',
    name: 'Mistral AI',
    aliases: ['mistral'],
    category: 'ai',
    icon: SiMistralai,
    colorClass: 'text-[#fa520f]',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    aliases: ['codeium'],
    category: 'ai',
    icon: SiWindsurf,
    colorClass: 'text-[#09b6a2]',
  },
  {
    id: 'v0',
    name: 'v0',
    aliases: ['v0 dev'],
    category: 'ai',
    icon: SiV0,
    colorClass: 'text-foreground',
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow',
    aliases: [],
    category: 'tooling',
    icon: SiTensorflow,
    colorClass: 'text-[#ff6f00]',
  },
  {
    id: 'discord',
    name: 'Discord',
    aliases: [],
    category: 'cms',
    icon: SiDiscord,
    colorClass: 'text-[#5865f2]',
  },
]

const techLookup = new Map<string, ITechItem>()

function registerTechLookups() {
  TECH_STACK_CATALOG.forEach((techItem) => {
    const keys = [techItem.id, techItem.name, ...techItem.aliases]
    keys.forEach((key) => {
      techLookup.set(normalizeTechKey(key), techItem)
    })
  })
}

export function normalizeTechKey(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '')
}

registerTechLookups()

export function getTechItemByName(name: string): ITechItem | undefined {
  if (!name.trim()) return undefined
  return techLookup.get(normalizeTechKey(name))
}

export function getCanonicalTechName(name: string) {
  return getTechItemByName(name)?.name ?? name.trim()
}

export function searchTechStack(query: string): ITechItem[] {
  const normalizedQuery = query.trim().toLowerCase()

  if (!normalizedQuery) return TECH_STACK_CATALOG

  return TECH_STACK_CATALOG.filter((techItem) => {
    if (techItem.name.toLowerCase().includes(normalizedQuery)) return true
    if (techItem.id.toLowerCase().includes(normalizedQuery)) return true
    return techItem.aliases.some((alias) => alias.toLowerCase().includes(normalizedQuery))
  })
}

export function groupTechStack(items: ITechItem[]): ITechStackGroup[] {
  return TECH_STACK_CATEGORY_ORDER.flatMap((category) => {
    const categoryItems = items.filter((item) => item.category === category)
    if (categoryItems.length === 0) return []
    return [{ category, items: categoryItems }]
  })
}

export function isTechNameSelected(selectedNames: string[], techName: string) {
  const targetKey = normalizeTechKey(getCanonicalTechName(techName))
  return selectedNames.some(
    (selectedName) => normalizeTechKey(getCanonicalTechName(selectedName)) === targetKey,
  )
}

export function toggleTechSelection(selectedNames: string[], techName: string) {
  const canonicalName = getCanonicalTechName(techName)

  if (isTechNameSelected(selectedNames, canonicalName)) {
    return selectedNames.filter(
      (selectedName) =>
        normalizeTechKey(getCanonicalTechName(selectedName)) !== normalizeTechKey(canonicalName),
    )
  }

  return [...selectedNames, canonicalName]
}
